### ISSUE TITLE
Dynamic Assembly Object

### ISSUE THREAD

**Issue by ccvelandres** [EIPStackGroup/OpENer#192]
Hi, I'm currently converting a project with static assembly object to dynamic assembly object.

The stack was ported to a STM32F3xx device with an ENC424J600 Ethernet Controller. Currently works fine but i don't know what version they used. The callback was still IApp_Init.

From the document, I need to implement the create and delete services and instance attribute 1 and 2 for the assembly object. Plus the instance attributes 1 and 2

Does the stack support dynamic assembly? If so, could I ask for some help regarding the configuration?

**Comment by ccvelandres** [comment]
If I'm correct, I need to add InsertAttribute Calls in createAssemblyObject for Attributes 1 and 2 right? 

`S_CIP_Instance *createAssemblyObject(EIP_UINT32 pa_nInstanceID, 
                                     EIP_BYTE * pa_data,
                                     EIP_UINT16 pa_datalength) {
  S_CIP_Class *pstAssemblyClass = NULL;

  if (NULL == (pstAssemblyClass = GetCipClass(CIP_ASSEMBLY_CLASS_CODE) ) ) {
    if (NULL == (pstAssemblyClass = createAssemblyClass() ) ) {
      return NULL;
    }
  }

  S_CIP_Instance *pstAssemblyInstance = AddCIPInstance(pstAssemblyClass, pa_nInstanceID); /* add instances (always succeeds (or asserts))*/

  S_CIP_Byte_Array *stAssemblyByteArray = (S_CIP_Byte_Array *) IApp_CipCalloc(1,
      sizeof(S_CIP_Byte_Array) );
  if ( stAssemblyByteArray == NULL) {
    return NULL; /*TODO remove assembly instance in case of error*/
  }

  stAssemblyByteArray->len =pa_datalength;
  stAssemblyByteArray->Data = pa_data;  
  
  // InsertAttribute( -- Attribute 1 -- );
  // InsertAttribute( -- Attribute 2 -- );
  
  InsertAttribute(pstAssemblyInstance, 3, kCipByteArray, stAssemblyByteArray, 
				  kSetAndGetAble);
  InsertAttribute(pstAssemblyInstance, 4, kCipUint, &(stAssemblyByteArray->len), 
				  kGetableSingle);

  return pstAssemblyInstance;
}`

And for the services, I'm not quite sure where to add them

**Comment by ccvelandres** [comment]
Okay, just found out the version used. It's around v1.2. I might need to update it first to the latest release :(

**Comment by CapXilinx** [comment]
Hi,

dynamic assemblies are currently not supported.
Object Instance services are injected into the Class instance, whereas Class Services are injected into a "hidden" meta-Class instance, so if you need additional services you have to add them respectively.

Updating is a very good idea, as a lot of things have changes in the specification and OpENer since V1.2

If there are any further questions feel free to ask.

Best,
Martin

**Comment by ccvelandres** [comment]
Just for clarification, dynamic assemblies are not supported by the stack, or does it just need some modifications which I was trying to do to support it? Sorry, I couldn't quite understand the "hidden" meta-Class instances you explained.

**Comment by CapXilinx** [comment]
No, they are not supported as object instances are allocated via static memory, mostly file-local global variables.

What I meant with the meta-Class: Object instances (Instance 1+) only hold instance variables, as each instance needs its own set of these. Instances services are shared over all Object Instances and are therefore stored in the Objects Class instance (Instance 0)

Again each Class instance (0) of each CIP object type needs its own set of Class variables, but Class services can again be shared. So in order to share the Class services another container is needed, and this other container is the Meta-Class instance, which is not accessible, but only be the Class Instances.

So there are three types in OpENer, the Object instances (1+) which represent the instances of the various CIP Object types, then the Class instances (0), which represent the Class instance of each CIP Object type supported, and last but not least, the Meta-Class, which cannot be accessed via CIP, which serves as the "blueprint" for alle Class instances (0), holding Class Services.

Best,
Martin

**Comment by ccvelandres** [comment]
Wasn't the object instances allocated on a linked list during runtime?  What if the instance variables are also allocated during runtime?

**Comment by CapXilinx** [comment]
The connection object instances are, but also they are allocated statically as a file-global array. In main the corresponding allocator and deallocator functions are assigned to the list instance.

Utilizing the List and the standard malloc and free functions you should be in theory able to dynamically create assembly objects. I just didn't implemented it.

**Comment by ccvelandres** [comment]
Got it. Good to know that dynamic assembly is not completely out of reach :) For now, I'll update our stack to the latest release. And we'll probably just make some workaround with the static assembly for now.

Thanks for the info!

Closing this issue now.
