### ISSUE TITLE
HandleReceivedExplictTcpData and HandleReceivedExplictUdpData return type inconsistency.

### ISSUE THREAD

**Issue by CapXilinx** [EIPStackGroup/OpENer#214]
Copied from #213 to separate the warning messages issue from the return type issue.

Originally submitted by @stm-at-esd

I think the HandleReceivedExplictTcpData() (and HandleReceivedExplictUdpData() also) need a rework to consistently return an EipStatus return type.

For HandleReceivedExplictTcpData() calling HandleReceivedSendRequestResponseDataCommand() or HandleReceivedSendUnitDataCommand() which in turn call NotifyConnectedCommonPacketFormat() that is returning the message size. I think at least these Handle*() should be converted to return EipStatus because the real message size is conveyed using outgoing_message.

HandleReceivedInvalidCommand() having itself a return type of EipStatus does return outgoing_message.used_message_length which is wrong in my opinion.

**Comment by stm-at-esd** [comment]
Hi,

I've been doing some  "homework" last weekend and would like to provide a patch that reworks the
mentioned functions to consistently return an EipStatus return type.

Here is the patch archive: 
[patches_190908.tar.gz](https://github.com/EIPStackGroup/OpENer/files/3591731/patches_190908.tar.gz)

The archive includes 4 patches. The first three are only cleanup patches. I think these can be applied after only a short examination.

The 4th patch includes the real changes. I have been running the CT16 successfully on this version.

In the sources I have marked some changed lines with TODO which need to be discussed because I'm not completely confident if they're correct:

**Source encap.c**

1. Function HandleReceivedSendUnitDataCommand() at line 660 and 683.
    In line 659 the _return_value_ was set to _kEipStatusOkSend_ in the old code. I believe it should 
    only be set to _kEipStatusOk_ there because it is done before checking 
    _receive_data->data_length_. If that would be < 6 then no response data will be generated and
   therefore the _return_value_ should be _kEipStatusOk_ only. If including the change on line 660
   then the change at line 683 is also needed to have the _return_value_ set to _kEipStatusOkSend_
   after GenerateEncapsulationHeader().
2. Function HandleReceivedSendRequestResponseDataCommand() at line 702 and 725.
   The same logic applies here as for the changes made for the previous topic.

Please confirm my changes (or roll them back) here and adjust the patch accordingly.

**Source cpf.c**

1. Two functions call AssembleLinearMessage() which possibly could return a value of -1 as error code. The calling functions are NotifyCommonPacketFormat() at line 54 and NotifyConnectedCommonPacketFormat() at line 165. I marked these two calls of AssembleLinearMessage() with at TODO comment because a bad CIP message response length will be entered in the Encapsulation Header if AssembleLinearMessage() returns -1. Please change or
remove the comment or change the code.
2. The function NotifyConnectedCommonPacketFormat() at line 199 previously returned the size of the outgoing_message. I don't know if the return value could be hardcoded. But at the moment I
create a EipStatus value by testing the _outgoing_message->used_message_length_ which at least
mimics the old behavior. I'm not quite sure if this solution is good.

I hope this helps to resolve this issue.

Best regards,
    Stefan
