### ISSUE TITLE
EncodeEPath bug

### ISSUE THREAD

**Issue by AitorArd** [EIPStackGroup/OpENer#56]
Hi,
I found a bug into EncodeEPath function. In the second line you are trying to add 8 bit data like 16 bit, AddIntToMessage(epath->path_size, message).

If I'm not wrong epath->path_size is an unsigned short int.

I hope I have helped. Regards!
Aitor

**Comment by CapXilinx** [comment]
Hello Aitor,
thank you for your feedback. Although you are correct that I am writing a 8 bit value as a 16 bit value, this is no bug as the AddIntToMessage function can handle this.

The fact that the epath->path_size is an unsigned short int instead of an unsigned int is the bug.
If you take a look in ciptypes.h a todo is already marking that the bug has to be fixed, but as all of my EPaths are currently small enough to fit into an unsigned short, the fix is currently on the lower end of my todo list.

Thank you again for your feedback and your interest in the OpENer!

Regards,
Martin
